### PR TITLE
Fix absolute/relative paths in results

### LINKED ISSUE #7953: Absolute / Relative URL mistake in search results
Hi there, thanks for providing this guide.
The links in the search results are malformed:

1. visit https://guide.freecodecamp.org/search
2. type something (`database`)
3. The result links to: `https://guide.freecodecamp.org/https://guide.freecodecamp.org/computer-science/databases/graph-databases`

I guess the code switching from relative to absolute URLs was mishandled.

### PR DESCRIPTION
**Pull request by Bouncey**
Closes #7953

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit 13dacaae3e2b1bfac67563b1231e0bdad6ca03d9

https://deploy-preview-7954--guide.netlify.com

**Comment by BerkeleyTrue** [comment]
Deploy preview ready!

Built with commit 116328e13009624bdf6ca5bb0245466119297229

https://deploy-preview-7954--guide.netlify.com

File: src/LayoutComponents/search/SearchBar.jsx [hunk 1]
```diff
@@ -35,35 +36,30 @@ function mapDispatchToProps(dispatch) {
...
-
   render() {
-    const { updateSearchTerm } = this.props;
+    const { updateIsSearching, updateSearchResults } = this.props;
     return (
       <FCCSearchBar
-        handleResults={this.handleResults}
+        handleResults={updateSearchResults}
         handleSearchingStatus={updateIsSearching}
-        handleSearchTerm={updateSearchTerm}
```
Comment (systimotic) [inline src/LayoutComponents/search/SearchBar.jsx]: The `updateSearchTerm` action is not dispatched at all anymore. `NoResults.jsx` needs to know the search term to decide to display "you didn't search" or "no results found." I tried adding it in the `handleSearchTerm` function, and that seemed to work properly.
