### PR TITLE
Inform users of no support for their browser

### LINKED ISSUE #217: Promise is not supported by IE 11
@QuincyLarson From which browser version are we supporting?

Currently the search will not work in IE11. 

We could:

- Add a polyfill for Promise's
- Refactor to not use Promise's
- Inform the user that the search page does not support their browser after doing a `'Promise' in window` check, and suggest they try chrome/firefox/edge

Personally I am not a fan of shipping polyfill to everyone regardless, and I like Promise's. So I would vote for the 'No support search page' and suggestion of upgrading.

### PR DESCRIPTION
**Pull request by Bouncey**
screenshot from 2017-09-03 23-31-49
screenshot from 2017-09-03 23-33-36
closes #217

### CODE REVIEW

File: src/pages/search/components/NoSupport.jsx [hunk 1]
```diff
@@ -0,0 +1,67 @@
+import React from 'react';
+import FontAwesome from 'react-fontawesome';
+import { Row, Col } from 'react-bootstrap';
+
+function NoSupport() {
+  return (
+    <div className='flexWrapper'>
```
Comment (systimotic) [inline src/pages/search/components/NoSupport.jsx]: This uses `.flexWrapper` and `.verticalAlign` from `NoResults/404`. Should we move those classes to global or some section specific to these kind of error pages?

File: src/pages/search/components/NoSupport.jsx [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+      <div className='verticalAlign'>
+        <h3 className='colourDarkGrey text-center'>
+          This page is not supported in your browser
+        </h3>
+        <p className='colourDarkGrey'>
+          {
+            'Either upgrade to the latest version or download one of the ' +
```
Comment (systimotic) [inline src/pages/search/components/NoSupport.jsx]: IE11 is the latest version of IE, but it doesn't support promises. How about "We suggest upgrading to the latest version of one of the browsers below"?

File: src/pages/search/components/Results.jsx [hunk 3]
```diff
@@ -34,27 +40,6 @@ function mapDispatchToProps(dispatch) {
   }, dispatch);
 }
 
-const faNames = {
-  challenge: 'free-code-camp',
-  guides: 'file-text',
-  youtube: 'youtube-play'
-};
-
-function FAIcon({ name }) {
```
Comment (systimotic) [inline src/pages/search/components/Results.jsx]: Good call on refactoring this 👍

File: src/pages/search/components/NoSupport.jsx (hunk 2 above)
Comment (Bouncey) [reply src/pages/search/components/NoSupport.jsx]: I thought edge was the latest version of IE? I linked to the edge download page, so if someone was on an older version of IE they would likely click the edge logo.

File: src/pages/search/components/Results.jsx (hunk 3 above)
Comment (Bouncey) [reply src/pages/search/components/Results.jsx]: I don't know why I put a wrapper around it in the first place 😕

File: src/pages/search/components/NoSupport.jsx (hunk 1 above)
Comment (Bouncey) [reply src/pages/search/components/NoSupport.jsx]: Probably, but I think it is out of scope for this PR. I noticed the latest version of Gatsby comes with a CSS Modules plugin, so I would like to give that a go if I can get the latest version of Gatsby to work here

**Comment by Bouncey** [comment]
What is the uncaught error? I cannot dev on a machine with IE on it. So I was half blind building this

File: src/pages/search/components/NoSupport.jsx (hunk 1 above)
Comment (Bouncey) [reply src/pages/search/components/NoSupport.jsx]: And I think it will be more like a CSS utils file, so `.flexSpaceAround` could go in it too

File: src/pages/search/components/NoSupport.jsx (hunk 2 above)
Comment (systimotic) [reply src/pages/search/components/NoSupport.jsx]: According to Microsoft, Edge and IE are different browsers. The logo's are similar enough that this might work, though. I'm still in favor of changing the copy.

**Comment by Bouncey** [comment]
@systimotic copy updated

**Comment by systimotic** [comment]
iexplore_2017-09-07_15-00-00
You can get the same error with more deletes by running `delete Promise` in the console in Chrome. It doesn't seem to impact functionality though. Hasn't been created by this PR, and doesn't functionality, so I think it's OK to leave it.
